function BacterialgrowthModule5DataBootcamp = importfile(workbookFile, sheetName, dataLines)
%IMPORTFILE Import data from a spreadsheet
%  BACTERIALGROWTHMODULE5DATABOOTCAMP = IMPORTFILE(FILE) reads data from
%  the first worksheet in the Microsoft Excel spreadsheet file named
%  FILE.  Returns the numeric data.
%
%  BACTERIALGROWTHMODULE5DATABOOTCAMP = IMPORTFILE(FILE, SHEET) reads
%  from the specified worksheet.
%
%  BACTERIALGROWTHMODULE5DATABOOTCAMP = IMPORTFILE(FILE, SHEET,
%  DATALINES) reads from the specified worksheet for the specified row
%  interval(s). Specify DATALINES as a positive scalar integer or a
%  N-by-2 array of positive scalar integers for dis-contiguous row
%  intervals.
%
%  Example:
%  BacterialgrowthModule5DataBootcamp = importfile("/Users/abiagealkeegan/Downloads/Bacterial growth Module 5 Data Bootcamp.xlsx", "Sheet1", [2, Inf]);
%
%  See also READTABLE.
%
% Auto-generated by MATLAB on 06-Sep-2023 15:54:50

%% Input handling

% If no sheet is specified, read first sheet
if nargin == 1 || isempty(sheetName)
    sheetName = 1;
end

% If row start and end points are not specified, define defaults
if nargin <= 2
    dataLines = [2, Inf];
end

%% Set up the Import Options and import the data
opts = spreadsheetImportOptions("NumVariables", 2);

% Specify sheet and range
opts.Sheet = sheetName;
opts.DataRange = dataLines(1, :);

% Specify column names and types
opts.VariableNames = ["TotalTimemin", "LBWbacOD"];
opts.VariableTypes = ["double", "double"];

% Import the data
BacterialgrowthModule5DataBootcamp = readtable(workbookFile, opts, "UseExcel", false);

for idx = 2:size(dataLines, 1)
    opts.DataRange = dataLines(idx, :);
    tb = readtable(workbookFile, opts, "UseExcel", false);
    BacterialgrowthModule5DataBootcamp = [BacterialgrowthModule5DataBootcamp; tb]; %#ok<AGROW>
end

%% Convert to output type
BacterialgrowthModule5DataBootcamp = table2array(BacterialgrowthModule5DataBootcamp);
end